name: Terraform Deployement

on:
  workflow_dispatch:
   inputs: 
      tfaction:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
           - "apply"
           - "destroy"
        
permissions: 
  contents: "read"
  id-token: "write"

jobs:
  aws-tf-action:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.9.1

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        run: terraform Plan
        
      - name: Terraform apply 
        if: ${{ github.event.inputs.tfaction == 'apply' }}
        run: terraform apply -auto-approve
        

      - name: Terraform Destroy 
        if: ${{ github.event.inputs.tfaction == 'destroy' }}
        run: terraform apply -auto-approve -destroy        

        
