name: "Terraform deployement"
on:
  workflow_dispatch:
permissions: 
  contents: "read"
  id-token: "write"
jobs:
  aws-tf-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "My code checkout"

      - name: Run a one-line script
        run: ech Hello, World!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
